### ISSUE TITLE
Spin up a project chat

### ISSUE THREAD

**Issue by mbestavros** [mbestavros/GeometricWeather#12]
With the F-Droid release out in the wild, there's been some interest in additional contribution to the app. A project chat to coordinate efforts would be beneficial, as suggested by @papjul [here](https://github.com/mbestavros/GeometricWeather/pull/10#issuecomment-720703448). Some options suggested were Element/Matrix or Mattermost, or just a simple Discord.

**Comment by mbestavros** [comment]
I've had a look at Matrix since I've heard really good things (plus, it's FOSS 😄)

I really like it. I've set up a community where developers can join and talk on matrix.org here:

https://matrix.to/#/+geometric-weather-foss:matrix.org

Closing this since it's done.

@papjul FYI ^

**Comment by LongJohn-Silver** [comment]
A community is a group of rooms, it is used similar to channels in Discord, you should create a room so that people can join. I wasn't able to do so through that link. @ is for users, # is for rooms and + is for communities.

Also, is the application dead?

**Comment by papjul** [comment]
Did you follow the link?
There is one public room available in our community.

**Comment by LongJohn-Silver** [comment]
Yes, but it says NIY, I on Android now.

**Comment by papjul** [comment]
Just tested on Android, you just have to click on "If you already have Element installed, you can open it here."

**Comment by LongJohn-Silver** [comment]
I don't see that, I see NYI: One group detail

**Comment by papjul** [comment]
Here is the direct link:
element://group/+geometric-weather-foss:matrix.org

Open this link in your Android browser. It will show you the list of apps installed on your Android device that can open this link.

**Comment by mbestavros** [comment]
@LongJohn-Silver The link I posted should work from a browser. I haven't tested onboarding people from mobile yet, so you're a good test case 😄

**Comment by LongJohn-Silver** [comment]
@papjul It doesn't work. Would it be too difficult to give me the direct address? It would be easier for everyone, and you could also leave the community address if anyone is interested. If there isnt one you can create it under the room settings.

**Comment by mbestavros** [comment]
@LongJohn-Silver Try this for a direct community address:

`+geometric-weather-foss:matrix.org`

I'm still pretty new to Matrix, so apologies for any hitches.
