### ISSUE TITLE
Add Fastlane file structure

### ISSUE THREAD

**Issue by mbestavros** [mbestavros/GeometricWeather#2]
Recommended by @IzzySoft as part of F-Droid packaging: https://gitlab.com/snippets/1895688

**Comment by IzzySoft** [comment]
Please let me know when both are merged and you've created a new tag with APK. I'd then add it to my repo as first step. Not only is adding it there faster, but my scanners often give a clue if something was overlooked or an app seems ready to be accepted at F-Droid.org.

Thanks a lot!
