### ISSUE TITLE
Apply for F-Droid inclusion

### ISSUE THREAD

**Issue by mbestavros** [mbestavros/GeometricWeather#3]
Hopefully doable now, with the proprietary binaries gone.

Prerequisites: #1 and #2.

**Comment by mbestavros** [comment]
From @IzzySoft on https://github.com/mbestavros/GeometricWeather/issues/7:

> Well, afraid the icon change will be required for that. I'm no designer either; but maybe just a "label" on top might suffice – like putting the text "free", "freed" or "FOSS" diagonally over the lower-right corner (`/`)?

Hmm, I'm not a fan of the label approach... Is there really no way it can be distributed with the same logo on F-Droid? Could an alternative logo exist for the F-Droid listing alone, while the app itself uses the existing one?

If not, I can look at creating an original one, though that will likely be a deeper task than I'd like. As I said, I'm not a designer.

**Comment by IzzySoft** [comment]
You can try – but those are the criteria given at F-Droid. Idea behind that is not to confuse a fork for its parent. If the name and the icon are identical, the two are easy to confuse (unless one looks for the AntiFeatures, like here). Not sure if you could get around the icon requirement by making the difference clear via the app name.

**Comment by mbestavros** [comment]
@IzzySoft I'm happy to try submitting with "Geometric Weather FOSS" or similar. If that doesn't work, I'll work on a new icon.

How would one do that?

**Comment by IzzySoft** [comment]
Just [open an RFP](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging). I'll chime in there as soon as the bot has picked it up (which it usually does within a day).

**Comment by mbestavros** [comment]
Cool, thanks! I'll look into that this weekend.

What's the average turnaround time like? I'm a little concerned that it could possibly be published before #8 gets resolved, which would lead to a scary Google Play Protect popup if it's not exempted.

**Comment by IzzySoft** [comment]
I cannot say which is faster (or takes longer), sorry. At F-Droid, it can be as fast as a few days – or take several weeks, depending on when a packager finds time to deal with it.

Funny stuff that GP thingy. Won't affect folks without GApps, luckily, who only trust F-Droid. And honestly, who trusts G? :smile:

**Comment by mbestavros** [comment]
@IzzySoft Understood.

> And honestly, who trusts G? 😄

I do (to an extent) 😛 

Quite frankly, I don't come from the same lineage (pun intended) as most F-Droid folk. I use a ton of very nonfree services daily and don't really have an issue with them.

That said, I _do_ appreciate the value of open source a lot (it's my current fulltime gig!), which is why I'm working on this 😄

Apologies for all the stupid questions, btw -- you've been super helpful though all of this, so thanks again.

**Comment by IzzySoft** [comment]
"We take your privacy, seriously!" (comma mine) is what I was playing at. And at the fact that G doesn't even *intend* to point out whether an app is tracker ridden, not to speak of the exent of it (I've encountered apps with 20 intrusive trackers; didn't count the others – so some apps seem to exist mostly for tracking the user, not the other way around). That's why I cannot really trust G. But admitted, I do to a degree: If I'm asked, it's still safer to install apps from there than from some unknown website. But then one should cross-check with at least *Exodus Privacy* to make sure not having picked a "bad apple"…

Oops. Apologies for the rant! No offense meant, and none taken. If we'd all think along the very same lines, wouldn't that be boring? :smile:

And: gladly done. I help when I can. But sometimes time is quite a limiting factor…

**Comment by robooneus** [comment]
Jumping in as I would love to see this app make it into fdroid - I am a designer and happy to help with a new icon if needed.

**Comment by mbestavros** [comment]
@robooneus That's fantastic! I still haven't opened an RFP (I've been waiting on #8), but I'd love to see what you come up with.

Obviously, given how design-focused the app is, I think it's important any alternative icon matches up well and feels "material". I don't have faith I'd do it justice myself, but if it fit in, I'd be open to including it.

**Comment by robooneus** [comment]
@IzzySoft you mentioned some requirements for icon changes from f-droid - is there any documentation for their specific requirements? I didn't find any after a quick look at the docs on their site.

I can easily recreate the original app icon + added requirements or something using the same design language.

**Comment by IzzySoft** [comment]
@robooneus I don't know where it is documented, I just remember it came up in an RFP for another app not that long ago. I'd say if it's clearly recognizable as "not the original one" it should be fine. Some resemblance IMHO shouldn't be a problem, as that would indicate its origin. It just shouldn't be too close (to not mistakenly confuse the two).

**Comment by mbestavros** [comment]
@robooneus @IzzySoft In any case, replacing the icon will mean more work for me as the maintainer of the fork, so if F-Droid takes a version without a redesigned icon, that's fine with me.

I'll fill out an RFP tomorrow to get the ball rolling and at least see if it's a blocker or not. If it is, then @robooneus is up. 😄

**Comment by mbestavros** [comment]
@IzzySoft I've pushed a new release: https://github.com/mbestavros/GeometricWeather/releases/tag/2.608.2-foss

I'm not seeing it reflected on the dependency tracker you liked to, however: https://apt.izzysoft.de/fdroid/index/apk/com.mbestavros.geometricweather

It also looks like it's only considering the initial repo push, and not the updated version that removed GMS. Is this an error?

In other news, I'm going to fill out the RFP now that I'm not observing the problem from #8 anymore (even if Google hasn't said anything about it either :stuck_out_tongue:)

**Comment by mbestavros** [comment]
@IzzySoft RFP opened! https://gitlab.com/fdroid/rfp/-/issues/1398

**Comment by IzzySoft** [comment]
Well, you've been a bit too impatient I guess – my updater only runs once a day, not necessarily exactly when you publish a release :rofl: And yay to the RFP – see you over there then!

**Comment by mbestavros** [comment]
@IzzySoft Anything else I should be doing with the RFP? Doesn't look like it's seen any movement since it was filed.

**Comment by IzzySoft** [comment]
Well, if you see a "red flag" there's something wrong. In case of "too-many-giturls" there's not even a notification mail sent out (as the bot doesn't create a comment then), so nobody was aware. I've now (hopefully) fixed that, let's see what the bot has to say.

**Comment by IzzySoft** [comment]
PS: Apart from that, your way of tagging causes issues.

1. you seem to delete "old" tags. Please don't.
2. the next tag often has the same versionCode in the APK the previous had. Bad practice: users never get update notifications for those, and F-Droid will refuse pulling and building such tags as it thinks "that version is already here".

So, in short:

* never delete tags (unless they are broken for some reasons)
* always increase `versionCode` with each new release.

Thanks!

**Comment by IzzySoft** [comment]
3. always make sure that the tag name corresponds to `versionName`. Currently it does NOT: "2.608.2" is not the same as "2.608". Again this would cause F-Droid to ignore the tag (and unfortunately make my updater download the very same version each day just to find out it collides with an existing one).

**Comment by mbestavros** [comment]
@IzzySoft Understood, thanks. I hadn't seen that guidance anywhere, but I'll be sure to follow it now that I'm aware.

Most of the changes I made to tags were because I was still making changes to what would eventually be shipped as a final APK. `2.608.2` I made as an exercise to test the rebasing process, but now that I know that causes problems, I'll stay away from doing that. Otherwise, with the fork working and pretty much complete now, I don't see any need to tag anything new until there's a new upstream release as well.

**Comment by IzzySoft** [comment]
Well, "2.608.2" is obviously greater than "2.608" – so my updater will continue pulling it each day just to quarantine it as "problematic" – so I'd really welcome a "matching tag" (or had to turn off auto-updates for your app). If you have a newer tag, that problem would be gone. If that's not at the horizon yet, maybe replace it by a "pure" 2.608 again? Please let me know (needs to be fixed for F-Droid anyway). Thanks!

**Comment by mbestavros** [comment]
@IzzySoft If I edit the problematic 2.608.2 tag back to 2.608, would that fix your issue? Or would removing the 2.608.2 tag altogether be best?

**Comment by IzzySoft** [comment]
"Renaming" it back to 2.608 would fix it for me (as the check "2.608 = 2.608" would tell my updater "there's nothing new") – and the APK would remain available for those who prefer picking it from your tag. That would also match versionName, so all would be fine. Thanks!

**Comment by mbestavros** [comment]
@IzzySoft I had to delete the older `2.608-foss` tag (since I can't create duplicate tags). However, the newest release is now tagged as it should be (as `2.608-foss`, renamed from `2.608.2-foss).

Hope that works!

**Comment by IzzySoft** [comment]
`git tag -d <tagName>` locally, in Github you can use the GUI (or maybe `git push <remoteName> --delete tag <tagName>`). But it seems you already figured. Shall all future tags have the `-foss` suffix? Asking for the RFP and setting up metadata with auto-update.

**Comment by mbestavros** [comment]
@IzzySoft Yes, that's the plan. Whenever upstream releases happen, I'll just tack on `-foss` to the new upstream version number.

**Comment by 6543** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7315

**Comment by mbestavros** [comment]
@6543 Fantastic to see! As someone new to the F-Droid process, what does this mean?

Anything I need to do at this point?

**Comment by IzzySoft** [comment]
@mbestavros basically it means that, to speed things up, @6543 did a part of the work a packager usually does: prepared the build information, made sure it works (builds with F-Droid tools) and now "just" needs to be reviewed and merged. It seems our packagers are a bit overworked (we have too few of them to keep up with the requests), so this helps tremendously lowering their workload and getting things done (thanks @6543!)

**Comment by mbestavros** [comment]
@IzzySoft Understood, thanks for the explanation. Hopefully we see some additional movement soon!

**Comment by mbestavros** [comment]
An update to those following, the [RFP](https://gitlab.com/fdroid/rfp/-/issues/1398) is done, and according to @IzzySoft, should be going live in a few days!

Keeping this issue open until it's live, but we're almost done 🙌

**Comment by IzzySoft** [comment]
> according to @IzzySoft, the app should be going live in a few days

… if all goes well. Remember Vagrant and our frequent "cannot bring up" loops, so I cannot give guarantees. But :crossed_fingers:

**Comment by LongJohn-Silver** [comment]
I started seeing the application yesterday, is it working or is it some weird bug because I already have it installed through Izzy's repository (I have them both on different stores, F-Droid on its own, and the latter in Aurora Droid)?

Also, will this continue to be developed on its own or will only stay up to date with the original author's repository?

**Comment by mbestavros** [comment]
> I started seeing the application yesterday, is it working or is it some weird bug because I already have it installed through Izzy's repository (I have them both on different stores, F-Droid on its own, and the latter in Aurora Droid)?

@LongJohn-Silver It is also [up](https://f-droid.org/en/packages/com.mbestavros.geometricweather/) for me! Thanks for the heads up -- this issue can now be considered closed!

> Also, will this continue to be developed on its own or will only stay up to date with the original author's repository?

My plan at this point is to simply keep this fork updated with upstream. If I do develop any new features (and I don't have any current plans to), it would make sense to propose them upstream to begin with so every Geometric Weather user is able to benefit from them.
