### ISSUE TITLE
left-over non-free dependencies

### ISSUE THREAD

**Issue by IzzySoft** [mbestavros/GeometricWeather#7]
First thanks for taking all that effort! You got rid of all those libraries that were causing the `Tracking` AntiFeature with the original app. But it's not yet "fully FOSS" unfortunately. My scanner reports two non-free elements:

* GMS (Google Mobile Services)
* Alipay (via the [AndroidDonate](https://github.com/didikee/AndroidDonate) library)

The latter might pass as "NonFreeNet" (which is unavoidable anyway due to AccuWeather), but the former is a show-stopper for F-Droid. Let's see what was triggering GMS to be shown:

```
./smali/com/google/android/gms/auth/api/signin/internal:
./smali/com/google/android/gms/base:
./smali/com/google/android/gms/common/annotation:
./smali/com/google/android/gms/common/api/internal:
./smali/com/google/android/gms/common/data:
./smali/com/google/android/gms/common/h:
./smali/com/google/android/gms/common/images:
./smali/com/google/android/gms/common/internal/safeparcel:
./smali/com/google/android/gms/common/server/converter:
./smali/com/google/android/gms/common/server/response:
./smali/com/google/android/gms/common/stats:
./smali/com/google/android/gms/common/util:
./smali/com/google/android/gms/dynamite:
./smali/com/google/android/gms/internal/base:
./smali/com/google/android/gms/internal/location:
./smali/com/google/android/gms/location/places:
./smali/com/google/android/gms/signin/internal:
```

Not being a dev, I can only guess here. Easy and sure guess going by your `build.gradle`:

```gradle
    // gms.
    implementation "com.google.android.gms:play-services-location:17.0.0"
```

That's certainly matched by `/com/google/android/gms/location/places`, and most of the other stuff (especially "common") are dependencies this one requests. Not sure whether the "signin" part is something separate – but that we will see once you got rid of the location dependency (if you can).

PS: Your app will go live in about 23h and then [can be found here](https://apt.izzysoft.de/fdroid/index/apk/com.mbestavros.geometricweather), so you can take a look at the library list for yourself.

**Comment by mbestavros** [comment]
@IzzySoft Thanks for the heads-up!

I've already been able to remove both dependencies on a test build, so that's positive. That said, I don't personally have an issue with GMS existing, so I might try and create two builds (one with, one without for F-Droid). Or not, and I'll just do the fully-free one without GMS. Unsure as of now.

On the payments front: how is WeChat viewed by F-Droid? Should I try and keep that in, or just rip out all payment code altogether?

Regardless, integrating both these changes into the build will take a bit of time, and I've done enough coding this weekend :stuck_out_tongue: I'll wait for the library list results and go from there.

**Comment by IzzySoft** [comment]
GMS: I personally do not care much either *in this case* – I don't have GApps on my device, and those calls would be mapped to microG. But for F-Droid, it's a show-stopper – and in my repo, I need to mark it NonFreeDep.

WeChat: I cannot tell for sure, we'll see then. If all it raises is NonFreeNet – that will be raised anyway (due to AccuWeather). If nothing is called as long as the user doesn't trigger it, it should not raise Tracking either. The library is at least open-source – I'm just not sure if the license clashes (the app is LGPL, the library MIT). If you want to be on the safe side, pull it out; it's China-only AFAIK (Alipay + WeiXin), so not really useful outside China.

Time: Take yours :smile: I didn't expect you solving all the worlds problems today, I give you another week for that :rofl:

**Comment by mbestavros** [comment]
@IzzySoft New build is up without GMS! https://github.com/mbestavros/GeometricWeather/releases/tag/2.608-foss

I've done as I said and produced two builds: one without GMS, which should be F-Droid ready, and one with GMS. I've found that the GMS version is tangibly faster to grab location, so I made it for personal use (but it's published for whoever wants it as well).

I've also not removed the `AndroidDonate` library just yet, as doing so would imply deeper changes than a simple dependency removal. If I can get away with including it, I might as well. BTW, I'm fairly certain MIT is compatible with LGPL. See [here](https://en.wikipedia.org/wiki/License_compatibility).

**Comment by IzzySoft** [comment]
Umpf, my updater says there's nothing new. Guess that means you just updated an existing tag and I need to pull the new APK manually and replace the existing one. Done. Confirm: NonFreeDep is gone (removed that AntiFeature), thanks and congrats! Will go live in about 9 hours from now.

**Comment by mbestavros** [comment]
Hmm, I'm not a fan of the label approach... Is there really no way it can be distributed with the same logo on F-Droid? Could an alternative logo exist for the F-Droid listing alone, while the app itself uses the existing one?

If not, I can look at creating an original one, though that will likely be a deeper task than I'd like. As I said, I'm not a designer.

**Comment by mbestavros** [comment]
@IzzySoft Let's move this discussion over to #3. I think I'd consider the title issue resolved.
